title: Kai Wu's Homepage
page-top-title: Kai Wu
top-section-bg-text: Per aspera ad Astra
home-subtitle: Kai Wu&ensp;|&ensp; B.S. @ Hangzhou Dianzi University
copyright-text: '&copy; Kai Wu 2025-2026. All Rights Reserved.'