title: KaiWu's Homepage
page-top-title: KaiWu
top-section-bg-text: Per aspera ad Astra
home-subtitle: KaiWu&ensp;|&ensp; B.S. @ Hangzhou Dianzi University
copyright-text: '&copy; KaiWu 2025-2026. All Rights Reserved.'